<a href="https://colab.research.google.com/github/davisvegh/Numpy-basics/blob/main/PythonForDataScience_week1_1_basic_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#NUMPY INDEXING AND ACCESSING ELEMENTS
#create a 2d python list and access the first and the second element?
#create a numpy array and access random elements?

# Get a specific element [row, col]
# With slicing - [row_start:row_end, col_start:col_end]
# Can leave out row_start / col_start if 0

#get a specific row
#get a specific column

# modify array

#example of indexing into 3d array

#NUMPY SHAPE-SHIFTING
#concatenate arrays
#vertically stacking vectors
#horizontal stack
#reshape array
#reshape a_flat to a rectangle matrix


#NUMPY MATH AND BROADCASTING
#create a 1d array and print it
#add value to all elements at once
#multiply all elements by a value
#divide all elements by a value
#add 2 arrays together
#multiply 2 arrays together
#take the sin/cos of arrays
#perform linear algebra operations on arrays
#transpose a 3d array to a 1d array

#LOAD DATA FROM FILE INTO NUMPY


[1, 2, 3, 4]


In [ ]:
#INITIALIZING NUMPY ARRAYS
#import numpy as np

#create a python list
#a_list = [1,2,3,4]
#print(a_list)

#create a numpy 1d array
#b = np.array([9.0,8.0,7.0,6.0])
#print(b)

#create a numpy 2d array
#c = np.array([[1,2,3,4],[5,6,7,8]])
#print(c)

#get dimension of both arrays
#print('The array B has %d dimension' % b.ndim)
#print("The array C has %d dimensions" % c.ndim)

#get shape of both arrays
#print(b.shape)
#print(c.shape)

#get type of both arrays
#print(b.dtype)
#print(c.dtype)

#get size of both arrays
#print(b.nbytes)
#print(c.nbytes)

32
64


In [ ]:
#import numpy as np

#MORE TYPES OF NUMPY INITIALIZATIONS
#create an all 0 matrix
#d = np.zeros((3,3))
#print(d)

#create an all 1 matrix
#ones = np.ones((3,3))
#print(ones)

#create a matrix filled with random numbers
#randomn = np.random.rand(3,2)
#print(randomn)

#create an identity matrix
#meye = np.eye(3)
#print(meye)

#create a matrix filled with random decimal numbers between 0-10
#randomdec = np.random.rand(4,2)*10
#print(randomdec)

#copy in numpy
#a = np.array([1,2,3])
#b = a.copy()

#b[1] = 99
#print(a)
#print(b)


In [ ]:
#NUMPY INDEXING AND ACCESSING ELEMENTS
#create a 2d python list and access the second row's third and fourth item
#a = [[1,2,3],[4,5,6]]
#a[1][2]

#create a numpy array and sh shape
#a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
#print(a.shape)

# Get a specific element [row, col]
# With slicing - [row_start:row_end, col_start:col_end]
# Can leave out row_start / col_start if 0
#a[:2,:-2]

#get a specific row
#row = a[1,:]
#print(row)

#get a specific column
#col = a[:,4]
#print(col)

# modify array
#a[:,2] = [6,9]
#print(a)

#example of indexing into 3d array
#a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
#print(f"The a array is:  \n {a}")

#print(f"\n The 1st row's first column's 0th element of the a array is: {a[1,1,0]}")

The a array is:  
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

 The 1st row's first column's 0th element of the a array is: 7


In [ ]:
#NUMPY SHAPE-SHIFTING
#concatenate arrays
#import numpy as np

a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9]])

#c = np.concatenate((a,b), axis = None)
#print(c)


#vertically stacking vectors
np.vstack([a,b])
#print(d)

#horizontal stack
#print("---")
#d = np.hstack(a)
#print(d)

#reshape array
#print(f"The shape of the array A is: {a.shape}")
#print(a)
#print("Reshaping the A array:")
#b = a.reshape(3,2)
#print(b)


#reshape a_flat to a rectangle matrix
#c = a.reshape(1,1)
#print(c)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Initializing Numpy Arrays


In [ ]:
a = [1, 2, 3, 4]  # normal python list
numpy_a = np.array([1, 2, 3, 4], dtype='int16') # numpy 1d array

In [ ]:
# numpy 2d array
b = np.array([
    [9.0,8.0,7.0],
    [6.0,5.0,4.0]
])

In [ ]:
# Get Dimension
# a.ndim
b.ndim

2

In [ ]:
# Get Shape
b.shape

(2, 3)

In [ ]:
# Get Type
print(b.dtype)

# Get Size
print(b.nbytes)

float64
48


# More types of NumPy initializations

In [ ]:
# All 0s matrix
np.zeros((5,6))

In [ ]:
# All 1s matrix
np.ones((3, 3))

In [ ]:
# Matrix filled with any number
np.full((5,2), 8)

array([[8, 8],
       [8, 8],
       [8, 8],
       [8, 8],
       [8, 8]])

In [ ]:
# identity matrix
np.eye(5)

In [ ]:
# Random decimal numbers between 0-10
np.random.rand(4,2) * 10

In [ ]:
# Copying in numpy
a = np.array([1,2,3])
b = a.copy() # REMEMBER TO DO THIS. Otherwise, when b is mutated, a also changes

b[1] = 100
print(a)
print(b)

#Numpy Indexing and Accessing Elements

In [ ]:
python_list = [
    ['apple', 'orange', 'banana'], 
    ['panda', 2, 100]]
python_list[1][2]

In [ ]:
a = np.array([
    [1,2,3,4,5,6,7],
    [8,9,10,11,12,13,14]
])
a.shape

In [ ]:
# Get a specific element [row, col]
# With slicing - [row_start:row_end, col_start:col_end]
# Can leave out row_start / col_start if 0
a[:2,:-2]

In [ ]:
# Get a specific row 
row = a[0, :]
print(row)

# Get a specific column
col = a[:, 4]
print(col)

In [ ]:
# Modify array
a[:,2] = [1,2]
print(a)

In [ ]:
# Example of indexing into 3D array

c = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
  ])
# print(c)

# access 1st row, 1st col, 0th value
print(c[1, 1, 0])

# Numpy Shape-shifting

In [ ]:
# Concatenating arrays
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
np.concatenate((arr1, arr2))

In [ ]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

In [ ]:
# Horizontal  stack
h1 = np.ones((4,5))
h2 = np.full((4,2), 2)

np.hstack((h1,h2))

In [ ]:
# Reshape array
a = np.full((4, 8), 3)
print(a)

a_flat = a.flatten()
print(a_flat)

# Reshap a_flat to a rectangle matrix
b = np.reshape(a_flat, (2, 16))
print(b)

# Numpy Math & Broadcasting

In [ ]:
a = np.array([1,2,3,4])
print(a)

In [ ]:
# Add value to all elements at once
print(a + 7)

In [ ]:
# Multiply all elements in a by value
print(a * 3)

In [ ]:
# Divide all elements in a by value
print(a / 2)

In [ ]:
# Add 2 arrays together
b = np.array([4, 5, 6, 7]) # Needs to be the same shape! 

print(a + b)

In [ ]:
# Multiply 2 arrays together
print(a * b) # Needs to be the same shape!

In [ ]:
# Take the sin / cos of arrays
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)
np.sin(a * b)

In [ ]:
# Perform linear algebra operations

# shape (2, 2)
a = np.array([
    [1, 2], 
    [2, 3]
])

# shape (3, 2)
b = np.array([
    [1, 2], 
    [2, 3],
    [3, 3]
])

# Error!
c = np.matmul(a, b)

In [ ]:
c = np.matmul(a, b.transpose()) # (2, 2) x (2, 3) => (2, 3)
print(c)

# Load data from file into Numpy

In [ ]:
filedata = np.genfromtxt('./sample_data/california_housing_train.csv', delimiter=',', skip_header=1)

print(filedata.shape)

In [ ]:
total_rooms = filedata[:, 3] 
total_rooms.shape

In [ ]:
print(min(total_rooms))
print(max(total_rooms))

In [ ]:
# concatenate a new column to existing data
num_persons_living = np.full((17000, 1), 4)

filedata = np.hstack((filedata, num_persons_living))
print(filedata.shape)